Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-07, with the labels that each got.

#109 chore(manifest): add supported platforms arduino
  library.json
Labels: Complexity: Low, Type: Task

#108 chore(manifest): update dependencies
  library.json
Labels: Complexity: Low, Type: Task

#107 fix(manifest): Correct Supported Platforms
  library.json
Labels: Complexity: Low, Type: Bugfix

#111 chore(transaction): update amounts json
  src/identities/address.cpp
  src/include/cpp-crypto/transactions/builder.h
  src/include/cpp-crypto/transactions/transaction.h
  src/transactions/builder.cpp
  src/transactions/deserializer.cpp
  src/transactions/serializer.cpp
  src/transactions/transaction.cpp
  test/transactions/builder.cpp
  test/transactions/deserializer.cpp
  test/transactions/serializer.cpp
  test/transactions/transaction.cpp
Labels: Complexity: High, Type: Task

#112 [arduino]chore(transaction): update amounts json
  src/identities/address.cpp
  src/transactions/builder.cpp
  src/transactions/builder.h
  src/transactions/deserializer.cpp
  src/transactions/serializer.cpp
  src/transactions/transaction.cpp
  src/transactions/transaction.h
Labels: Complexity: Low, Type: Task

#114 [arduino] docs: update changelog and merge #93 from master
  CHANGELOG.md
  README.md
Labels: Complexity: Low, Type: Documentation

#113 chore: update changelog and merge #93 from master
  CHANGELOG.md
  README.md
Labels: Complexity: Low, Type: Task

#117 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#118 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
