Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-09, with the labels that each got.

#135 chore: Add support for Visual Studio 2019
  CMakeSettings.json
Labels: Complexity: Medium, Status: Contributor Approved, Type: Task

#143 ci: setup github action workflow for testing
  .circleci/config.yml
  .github/workflows/test.yml
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/platformio.cpp
  .github/workflows/test/script_arduino.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
Labels: Complexity: Medium, Status: Needs Review

#141 test: Break Up Tests
  test/platformio.ini
Labels: Complexity: Medium

#146 fix(crypto): fix crash in tests
  src/crypto/curve.cpp
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved

#145 chore: fix PIO Builds
  .gitignore
  platformio.ini
  src/iot/platformio.cpp
  test/managers/fee_manager.cpp
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved

#147 ci: update arduino triggers
  .github/workflows/test/script_arduino.sh
Labels: Complexity: Low
