Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-11, with the labels that each got.

#185 chore: add +x to scripts
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_arduino.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  extras/ARDUINO_IDE.sh
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#190 refactor: remove usage of monolithic arkCrypto.h
  examples/arduino/ESP32/ESP32.ino
  examples/arduino/ESP32/arkCrypto_esp32.h
  examples/arduino/ESP8266/ESP8266.ino
  examples/arduino/ESP8266/arkCrypto_esp8266.h
  src/include/cpp-crypto/arkCrypto.h
  test/common/configuration.cpp
  test/common/fee_policy.cpp
  test/common/network.cpp
  test/defaults/static_fees.cpp
  test/defaults/transaction_types.cpp
  test/transactions/deserializer_multi_signature_registration.cpp
  test/transactions/deserializer_second_signature_registration.cpp
  test/transactions/deserializer_transfer.cpp
  test/transactions/deserializer_vote.cpp
  test/transactions/serializer.cpp
  test/transactions/transaction.cpp
  test/transactions/transaction_to_json_type_0.cpp
  test/transactions/transaction_to_json_type_1.cpp
  test/transactions/transaction_to_json_type_2.cpp
  test/transactions/transaction_to_json_type_3.cpp
Labels: Complexity: Medium, Status: Member Approved, Type: Refactor

#191 chore: move global data to function local
  src/crypto/message.cpp
  src/crypto/slot.cpp
  src/lib/rfc6979/rfc6979.h
  src/utils/hex.hpp
  src/utils/str.hpp
Labels: Complexity: Low, Status: Member Approved, Type: Task

#194 build: hide cmake warnings
  cmake/extern/ArduinoJson.txt.in
  cmake/extern/BIP66.txt.in
  cmake/extern/GTest.txt.in
  cmake/extern/uECC.txt.in
Labels: Complexity: Low

#196 chore(docs): add c++11 badge
  README.md
Labels: Complexity: Low, Type: Task
