Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-05, with the labels that each got.

#83 fix: improve Windows support.
  CHANGELOG.md
  src/transactions/transaction.cpp
  src/utils/message.cpp
Labels: Complexity: Low, Type: Bugfix

#87 misc: Disable PlatformIO ESP8266 Tests
  CHANGELOG.md
  test/platformio.ini
Labels: Complexity: Low, Type: Maintenance

#84 feat: Increase VendorField Size
  CHANGELOG.md
  library.json
  library.properties
  src/transactions/transaction.cpp
Labels: Complexity: Low, Type: Feature

#85 fix: 0 ARKtoshi amount handling
  CHANGELOG.md
  src/include/cpp-crypto/transactions/builder.h
  src/transactions/builder.cpp
  src/transactions/transaction.cpp
  test/transactions/builder.cpp
Labels: Complexity: Low, Type: Bugfix

#89 [WIP]test: Add Appveyor CI Support
  .appveyor.yml
  CHANGELOG.md
Labels: Complexity: Low, Test: Unit

#92 refactor(slots): Improve Slots Implementations
  CHANGELOG.md
  platformio.ini
  src/helpers/crypto_helpers.h
  src/lib/stl/array
  src/lib/stl/cassert
  src/lib/stl/cctype
  src/lib/stl/cstddef
  src/lib/stl/cstdint
  src/lib/stl/cstdio
  src/lib/stl/cstring
  src/lib/stl/details/to_string.h
  src/lib/stl/memory
  src/utils/slot.cpp
  test/platformio.ini
Labels: Complexity: High, Type: Refactor

#94 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#96 chore: use correct field separator in keywords.txt
  keywords.txt
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved
