Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-08, with the labels that each got.

#122 chore: Visual Studio Support
  CMakeSettings.json
  test/common/fee_policy.cpp
  test/helpers/crypto.cpp
  test/helpers/encoding/hex.cpp
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved

#124 fix: Add missing initialization for transaction version
  src/include/cpp-crypto/transactions/builder.h
  src/include/cpp-crypto/transactions/transaction.h
  src/transactions/builder.cpp
  src/transactions/transaction.cpp
  test/transactions/transaction.cpp
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Bugfix

#125 feat: Add debug support for VS Code
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  CMakeLists.txt
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved

#127 chore: Remove extra copies and add const
  src/helpers/crypto.cpp
  src/helpers/crypto.h
  src/identities/address.cpp
  src/identities/privatekey.cpp
  src/identities/publickey.cpp
  src/identities/wif.cpp
  src/include/cpp-crypto/common/network.hpp
  src/include/cpp-crypto/identities/address.hpp
  src/include/cpp-crypto/identities/privatekey.hpp
  src/include/cpp-crypto/identities/publickey.hpp
  src/include/cpp-crypto/identities/wif.hpp
  src/include/cpp-crypto/transactions/builder.h
  src/include/cpp-crypto/transactions/serializer.h
  src/include/cpp-crypto/transactions/transaction.h
  src/transactions/builder.cpp
  src/transactions/serializer.cpp
  src/transactions/transaction.cpp
  src/utils/message.cpp
  src/utils/message.h
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Task

#128 refactor: signing
  src/CMakeLists.txt
  src/crypto/curve.cpp
  src/crypto/curve.hpp
  src/crypto/hash.cpp
  src/helpers/crypto.cpp
  src/helpers/crypto.h
  src/lib/bcl/Base58Check.cpp
  src/lib/bcl/Base58Check.hpp
  src/lib/bcl/CurvePoint.cpp
  src/lib/bcl/CurvePoint.hpp
  src/lib/bcl/Ecdsa.cpp
  src/lib/bcl/Ecdsa.hpp
  src/lib/bcl/FieldInt.cpp
  src/lib/bcl/FieldInt.hpp
  src/lib/bcl/Ripemd160.cpp
  src/lib/bcl/Ripemd160.hpp
  src/lib/bcl/Sha256.cpp
  src/lib/bcl/Sha256.hpp
  src/lib/bcl/Sha256Hash.cpp
  src/lib/bcl/Sha256Hash.hpp
  src/lib/bcl/Sha512.cpp
  src/lib/bcl/Sha512.hpp
  src/lib/bcl/Uint256.cpp
  src/lib/bcl/Uint256.hpp
  src/lib/bcl/Utils.cpp
  src/lib/bcl/Utils.hpp
  src/transactions/deserializer.cpp
  src/transactions/transaction.cpp
  src/utils/base58.cpp
  src/utils/message.cpp
  src/utils/message.h
  test/CMakeLists.txt
  test/crypto/curve.cpp
  test/helpers/crypto.cpp
Labels: Complexity: High, Status: In Progress, Type: Refactor

#133 refactor: utils
  .circleci/script_desktop.sh
  CHANGELOG.md
  docs/INSTALL_ARDUINO.MD
  docs/cpp.md
  examples/arduino/ESP32/ESP32.ino
  examples/cmake_example/main.cpp
  examples/platformio_example/src/main.ino
  extras/ARDUINO_IDE.sh
  src/CMakeLists.txt
  src/crypto/curve.cpp
  src/crypto/message.cpp
  src/crypto/slot.cpp
  src/include/cpp-crypto/arkCrypto.h
  src/include/cpp-crypto/crypto/message.hpp
  src/include/cpp-crypto/crypto/slot.hpp
  src/transactions/builder.cpp
  src/transactions/deserializer.cpp
  src/transactions/serializer.cpp
  src/transactions/transaction.cpp
  src/utils/crypto_helpers.h
  src/utils/json.h
  src/utils/message.cpp
  src/utils/slot.cpp
  test/CMakeLists.txt
  test/crypto/curve.cpp
  test/crypto/message.cpp
  test/crypto/slot.cpp
  test/fixtures/message.hpp
  test/transactions/transaction.cpp
  test/utils/crypto_helpers.cpp
  test/utils/hex.cpp
  test/utils/message.cpp
Labels: Complexity: High, Status: In Progress, Type: Refactor

#121 style: formatting, coverage, and improvements
  .circleci/clang_tidy.sh
  .circleci/install_platform_io.sh
  .circleci/platformio.cpp
  .circleci/script_desktop.sh
  .circleci/script_platform_io.sh
  CHANGELOG.md
  docs/cpp.md
  extras/ARDUINO_IDE.sh
  keywords.txt
  platformio.ini
  src/CMakeLists.txt
  src/common/configuration.cpp
  src/common/network.cpp
  src/crypto/message.cpp
  src/crypto/slot.cpp
  src/defaults/static_fees.cpp
  src/include/cpp-crypto/arkCrypto.h
  src/include/cpp-crypto/common/configuration.hpp
  src/include/cpp-crypto/common/fee_policy.hpp
  src/include/cpp-crypto/common/network.hpp
  src/include/cpp-crypto/defaults/fee_policies.hpp
  src/include/cpp-crypto/defaults/static_fees.hpp
  src/include/cpp-crypto/defaults/transaction_types.hpp
  src/include/cpp-crypto/networks/devnet.hpp
  src/include/cpp-crypto/networks/mainnet.hpp
  src/include/cpp-crypto/networks/networks.hpp
  src/include/cpp-crypto/networks/testnet.hpp
  src/managers/fee_manager.cpp
  src/managers/fee_manager.hpp
  src/managers/network_manager.cpp
  src/managers/network_manager.hpp
  src/networks/devnet.cpp
  src/networks/mainnet.cpp
  src/networks/testnet.cpp
  src/transactions/builder.cpp
  src/transactions/deserializer.cpp
  src/transactions/serializer.cpp
  src/transactions/transaction.cpp
  src/utils/json.h
  test/common/configuration.cpp
  test/common/fee_policy.cpp
  test/common/network.cpp
  test/crypto/slot.cpp
  test/defaults/static_fees.cpp
  test/defaults/transaction_types.cpp
  test/managers/fee_manager.cpp
  test/managers/network_manager.cpp
  test/networks/devnet.cpp
  test/networks/mainnet.cpp
  test/networks/testnet.cpp
  test/platformio.ini
  test/transactions/builder.cpp
  test/transactions/deserializer.cpp
  test/utils/crypto_helpers.cpp
Labels: Complexity: Undetermined, Status: In Progress, Type: Standards

#131 Migrate to GTest
  test/iot/gtest/gtest.h
  test/iot/test_main.cpp
  test/platformio.ini
  test/transactions/transaction.cpp
Labels: Complexity: Medium, Status: Contributor Approved

#137 chore: Add missing +x to scripts
  build.sh
  run_tests.sh
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Task
