Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-10, with the labels that each got.

#150 ci: setup windows workflow
  .appveyor.yml
  .github/workflows/test.yml
Labels: Complexity: Low, Type: Task

#152 ci: pass environment variables to steps
  .github/workflows/test.yml
Labels: Complexity: Medium

#159 ci: setup cppcheck for codeclimate
  .codeclimate.yml
Labels: Complexity: Low

#163 ci: add coverage workflow
  .codeclimate.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  CMakeLists.txt
  README.md
  test/CMakeLists.txt
Labels: Complexity: Medium

#165 chore: merge master => develop
  .codeclimate.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/platformio.cpp
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  CHANGELOG.md
  CMakeLists.txt
  CODEOWNERS
  README.md
  library.json
  library.properties
  test/CMakeLists.txt
Labels: Complexity: Medium, Type: Task

#164 fix: platformio tests src_filter
  test/platformio.ini
Labels: Complexity: Low, Type: Bugfix

#167 fix: cmake warnings
  cmake/extern/ArduinoJson.txt.in
  cmake/extern/BIP66.txt.in
  cmake/extern/GTest.txt.in
  cmake/extern/uECC.txt.in
Labels: Complexity: Low, Type: Bugfix

#171 ci: split coverage workflows
  .github/workflows/codeclimate.yml
  .github/workflows/coverage.yml
Labels: Complexity: Low

#170 ci: call correct EXE for windows tests
  .github/workflows/test.yml
Labels: Complexity: Low, Status: Contributor Approved, Status: Member Approved

#172 test: break up unit tests to support platforms with limited RAM
  test/CMakeLists.txt
  test/crypto/curve.cpp
  test/crypto/curve_ecdsa_sign.cpp
  test/crypto/curve_ecdsa_sign_null_hash32_privatekey.cpp
  test/crypto/curve_ecdsa_sign_null_hash32_sha256.cpp
  test/crypto/curve_ecdsa_sign_null_pk.cpp
  test/crypto/curve_publickey.cpp
  test/crypto/curve_verify_invalid.cpp
  test/crypto/curve_verify_valid.cpp
  test/crypto/message.cpp
  test/crypto/message_sign.cpp
  test/crypto/message_verify.cpp
  test/fixtures/identity.hpp
  test/identities/address.cpp
  test/identities/keys.cpp
  test/identities/keys_publickey.cpp
  test/identities/privatekey.cpp
  test/identities/publickey.cpp
  test/identities/wif.cpp
  test/transactions/builder.cpp
  test/transactions/builder_transfer_custom_network.cpp
  test/transactions/deserializer.cpp
  test/transactions/deserializer_delegate_registration.cpp
  test/transactions/deserializer_multi_signature_registration.cpp
  test/transactions/deserializer_second_signature_registration.cpp
  test/transactions/deserializer_transfer.cpp
  test/transactions/deserializer_vote.cpp
  test/transactions/transaction.cpp
  test/transactions/transaction_to_array.cpp
  test/transactions/transaction_to_json.cpp
Labels: Bounty: Tier 4, Complexity: Undetermined, Status: Contributor Approved

#169 test: fix ESP8266 Unit Tests
  .gitignore
  test/iot/test_main.cpp
  test/platformio.ini
Labels: Complexity: Undetermined, Status: Contributor Approved

#175 Remove upload port used for debugging
  test/platformio.ini
Labels: Complexity: Low, Status: Member Approved

#178 fix: Fix transaction::to_array tests on ESP8266
  test/CMakeLists.txt
  test/platformio.ini
  test/transactions/transaction_to_array.cpp
  test/transactions/transaction_to_array_type_0.cpp
  test/transactions/transaction_to_array_type_1.cpp
  test/transactions/transaction_to_array_type_2.cpp
  test/transactions/transaction_to_array_type_3.cpp
Labels: Complexity: High, Status: Member Approved, Type: Bugfix

#180 fix: Fix transaction::to_json tests on ESP8266
  test/CMakeLists.txt
  test/platformio.ini
  test/transactions/transaction_to_json.cpp
  test/transactions/transaction_to_json_type_0.cpp
  test/transactions/transaction_to_json_type_1.cpp
  test/transactions/transaction_to_json_type_2.cpp
  test/transactions/transaction_to_json_type_3.cpp
Labels: Complexity: High, Status: Member Approved, Type: Bugfix

#182 ci: add esp8266 arduino cli configs back
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/script_arduino.sh
Labels: Complexity: Low, Status: Member Approved

#181 feat: disable wifi on esp8266 during tests
  test/iot/platform.hpp
  test/iot/test_main.cpp
  test/platformio.ini
Labels: Complexity: Low, Status: Member Approved, Type: Feature
