Repository ArkEcosystem/cpp-crypto, pull requests merged in 2019-02, with the labels that each got.

#55 misc: Update Library Config
  library.json
Labels: Status: Contributor Approved

#57 fix: library config examples' paths
  library.json
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Bugfix

#58 fix: Remove Unneeded/Redundant Manifest Fields
  library.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#62 chore: setup code owners
  CODEOWNERS
Labels: Complexity: Low, Status: Needs Review, Type: Task

#60 chore: Automate Arduino Script
  extras/ARDUINO_IDE.sh
Labels: Complexity: Low, Status: Needs Review

#61 test: Add Arduino CircleCI Config
  .circleci/config.yml
  .circleci/install_arduino.sh
  .circleci/script_arduino.sh
Labels: Complexity: Low, Status: Needs Review, Test: Unit

#63 fix: Arduino CI
  .circleci/script_arduino.sh
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#66 chore: bump version
  CHANGELOG.md
  library.json
  library.properties
  platformio.ini
Labels: Complexity: Low, Status: Needs Review, Type: Task

#70 Fix PIO CI Builds
  platformio.ini
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Status: Needs Review

#69 fix: Update Build Flag
  library.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#71 chore(release): 0.3.1
  CHANGELOG.md
  library.json
  library.properties
Labels: Complexity: Low, Status: Needs Review, Type: Task
